branches:
  only:
    - master

language: node_js

node_js:
  - "0.11"

before_script:
  - "npm install -g grunt-cli"
  - "npm install -g bower"
  - "npm install"
  - "bower install"

script:
  - "npm run build"

notifications:
  email:
    - ram@hiddentao.com
